#!/bin/sh
#cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cp 0/alpha.water.orig 0/alpha.water
cp 0/U.orig 0/U
runApplication blockMesh
#runApplication setFields
runApplication $(getApplication)
#runApplication decomposePar
#runParallel $(getApplication)
#runApplication reconstructPar

#------------------------------------------------------------------------------
