#!/bin/sh
#cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cp -r startMoments/0 ./
runApplication blockMesh
runApplication setFields
#runApplication $(getApplication)
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar
python3 prepareDNSData.py > log.python

#------------------------------------------------------------------------------
